### ISSUE TITLE
Last tasks before v0.17

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#278]
It's IMHO time to release a new (major) version, to bring users all the speed and usability improvements added. I'd like to release during the weekend of 13-15 October.

I think I'll write the release announcement this time, unless @sriemer wants to do it himself.

This issue tracks the last things needed before we can release, @scanmem/committers feel free to edit this checklist as you see fit or discuss below.

- [x] Test that the android build still works
- [x] Actually write a release announcement
- [x] Update the man page. Awaiting ok, see https://github.com/scanmem/scanmem/issues/278#issuecomment-335909455
- [x] Review #169 , last from old v0.17 issues.
- [x] Review #283 (last of my master)
- [x] It's 2017, update some copyrights
- [x] Chat channel? Done: see https://github.com/scanmem/scanmem/issues/278#issuecomment-335219558
- [x] Talk to packagers about libsm/sm split and readline dep (see https://github.com/scanmem/scanmem/issues/278#issuecomment-334523293 )

**Comment by sriemer** [comment]
Go for it! Thank you very much for taking over maintaining for `v0.17`! 🥇  I really appreciate that and I also like the improvements done for `v0.17`. Bringing it to the distributions is the next step after the release.

**Comment by 12345ieee** [comment]
Thanks, @sriemer !

On the distributions topic, the split between libsm and sm is IMHO complete.
It should be possible to ship libsm and libsm-dev packages, and have them NOT depend on libreadline/terminfo, as I have confined readline use in the CLI frontend only, so other front-ends based on whatever input methods can be developed.

If you have any problems convincing the debian packaging tools of these facts, do tell, as I had some issues configuring autotools.

**Comment by vido89** [comment]
Great news and good work :)

**Comment by rubenvereecken** [comment]
I love what you're doing here, and good work setting yourself a deadline for the v0.17 release!

Have you considered having a channel for more direct communication between contributors? I'm definitely interested in this project and think I could contribute as I go about using it. For one, I used the Android build yesterday and can relay my experience with it, update the script's UX since it does need some loving.

**Comment by 12345ieee** [comment]
Thanks, @rubenvereecken .
The android build definitely needs some love and testing, and we welcome any help on that front.

As for a channel, I wanted to integrate a [gitter chat](https://gitter.im), but haven't got around to do it.
Maybe it's time.
I considered IRC, but we are too few and I have no always-connected hardware to run an always-online IRC bot.
I'm open to alternative suggestions.

**Comment by rubenvereecken** [comment]
I really don't want to push any external services because I don't care enough, but I've used Gitter and Slack with open source projects and found both worked well and the latter a preferable. I feel people are getting used to seeing Slack.

And yeah on the note of IRC, neither do I. I've used Slack's IRC interface for a while though.

Best to be set up by the main contributor of course.

**Comment by 12345ieee** [comment]
Going on on the chat choice, I had a look at both gitter & slack, they are pretty much equivalent in layout/capabilities/GH support.

I also use discord, but that one is geared towards videogamers, and skype, which I hate with all my heart, so they're both excluded.

IRC is excluded as well as said above.

So, any preference between gitter and slack from @scanmem/committers ?

**Comment by bkazemi** [comment]
Never used this kind of feature, so no preference from me.

**Comment by 12345ieee** [comment]
Given no preference, I followed @rubenvereecken 's suggestion and went with slack.
It looks nice, here is an [invite link](https://join.slack.com/t/scanmem/shared_invite/enQtMjUzMDYxNDE0ODAxLWE5MjUzNjIzMmYyZmRhMTJiNjM4OWU4NjM2NTMxNDVmODZmNDY3ZjMyYjM2ZjQ1ZjUzYmFkYTNiNTYxM2M4ZGM) for who's interested.

**Comment by 12345ieee** [comment]
The manpage update is here: 12345ieee/scanmem@2c3a01e , have a look.

**Comment by rubenvereecken** [comment]
Manpage looks good to me!

**Comment by 12345ieee** [comment]
I've written a release announcement and I plan to upload it and release v0.17 tomorrow morning.
(You guys have 8 hrs to try to find showstopper bugs 😄 )

Many thanks to everybody that contributed to this release.

**Comment by 12345ieee** [comment]
Closing, as we actually released a while ago.

I'll open a new thread to discuss features for 0.18 .
